package com.springboot.qa.qasystem.model;

import java.io.Serializable;
import java.util.Date;

public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.qid
     *
     * @mbg.generated
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.aids
     *
     * @mbg.generated
     */
    private String aids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_type
     *
     * @mbg.generated
     */
    private Integer qType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.qid
     *
     * @return the value of question.qid
     *
     * @mbg.generated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.qid
     *
     * @param qid the value for question.qid
     *
     * @mbg.generated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.uid
     *
     * @return the value of question.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.uid
     *
     * @param uid the value for question.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.aids
     *
     * @return the value of question.aids
     *
     * @mbg.generated
     */
    public String getAids() {
        return aids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.aids
     *
     * @param aids the value for question.aids
     *
     * @mbg.generated
     */
    public void setAids(String aids) {
        this.aids = aids == null ? null : aids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_type
     *
     * @return the value of question.q_type
     *
     * @mbg.generated
     */
    public Integer getqType() {
        return qType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_type
     *
     * @param qType the value for question.q_type
     *
     * @mbg.generated
     */
    public void setqType(Integer qType) {
        this.qType = qType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param createTime the value for question.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.modify_time
     *
     * @return the value of question.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.modify_time
     *
     * @param modifyTime the value for question.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question
     *
     * @return the value of question.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question
     *
     * @param question the value for question.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }
}